# Site settings
title: OpenShift Origin
email: noreply@redhat.com
description: "This site has moved! Check out http://www.openshift.org/"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openshift.github.io" # the base hostname & protocol for your site
github_username: openshift

# Build settings
markdown: kramdown

# Redirects setup
gems:
  - jekyll-redirect-from
